Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,6 @@
-name: Laba1
+name: Python App CI
+
+
 
 on:
 
@@ -12,7 +14,6 @@ on:
 
 
 
-
 jobs:
 
   build:
@@ -21,10 +22,9 @@ jobs:
 
 
 
-
     steps:
 
-    - name: Checkout Repository
+    - name: Checkout repository
 
       uses: actions/checkout@v2
 
@@ -40,16 +40,18 @@ jobs:
 
 
 
-    - name: Install Dependencies
+
+    - name: Install dependencies
 
       run: |
 
-        python -m pip install --upgrade pip
+        if [ -f requirements.txt ]; then
 
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          pip install -r requirements.txt
+
+        fi
 
         pip install flake8 pytest
-
 
 
 
@@ -57,6 +59,12 @@ jobs:
 
       run: |
 
-        # stop the build if there are Python syntax errors or undefined names
+        # make flake8 exit with non-zero exit code on error
 
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || exit 1
+
+
+
+    - name: Test with pytest
+
+      run: pytest
